apiVersion: v1
kind: ConfigMap
metadata:
  name: minio
  namespace: plugin-tests-prod
data:
  host: "http://minio:9000"
  region: "us-east-1"
  bucket: "plugin-tests-artifacts"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio
  namespace: plugin-tests-dev
data:
  host: "http://minio:9000"
  region: "us-east-1"
  bucket: "plugin-tests-artifacts"
