apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server
  namespace: plugin-tests-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tests.plugins.vultisig.com
      secretName: server-tls
  rules:
    - host: tests.plugins.vultisig.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server
  namespace: plugin-tests-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tests-dev.plugins.vultisig.com
      secretName: server-tls
  rules:
    - host: tests-dev.plugins.vultisig.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 8080
