apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: plugin-tests-prod
type: Opaque
stringData:
  dsn: "CHANGE_ME"
  password: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: plugin-tests-dev
type: Opaque
stringData:
  dsn: "CHANGE_ME"
  password: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: plugin-tests-prod
type: Opaque
stringData:
  uri: "CHANGE_ME"
  password: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: plugin-tests-dev
type: Opaque
stringData:
  uri: "CHANGE_ME"
  password: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: plugin-tests-prod
type: Opaque
stringData:
  root-user: "CHANGE_ME"
  root-password: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: plugin-tests-dev
type: Opaque
stringData:
  root-user: "CHANGE_ME"
  root-password: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption
  namespace: plugin-tests-prod
type: Opaque
stringData:
  secret: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption
  namespace: plugin-tests-dev
type: Opaque
stringData:
  secret: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
  namespace: plugin-tests-prod
type: Opaque
stringData:
  secret: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
  namespace: plugin-tests-dev
type: Opaque
stringData:
  secret: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  namespace: plugin-tests-prod
type: Opaque
stringData:
  vault-b64: "CHANGE_ME"
  server-vault-b64: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  namespace: plugin-tests-dev
type: Opaque
stringData:
  vault-b64: "CHANGE_ME"
  server-vault-b64: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: plugin-tests-prod
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: CHANGE_ME_BASE64
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: plugin-tests-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: CHANGE_ME_BASE64
