apiVersion: v1
kind: ServiceAccount
metadata:
  name: plugin-tests-worker
  namespace: plugin-tests-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plugin-tests-worker
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "delete", "get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plugin-tests-worker
subjects:
  - kind: ServiceAccount
    name: plugin-tests-worker
    namespace: plugin-tests-system
roleRef:
  kind: ClusterRole
  name: plugin-tests-worker
  apiGroup: rbac.authorization.k8s.io
